### ISSUE TITLE
Create Home Assistant add-on or custom component.

### ISSUE THREAD

**Issue by DarwinData** [mobilityhouse/ocpp#100]
Would this be possible?  It would be amazing.
thanks!

**Comment by OrangeTux** [comment]
I have to check HA APIs to so if it's possible. First of all, what do you expect from the integration? How do you want to use the integration?

**Comment by DarwinData** [comment]
We have a Chevy Volt and a Charge Point charger.  I would like to track the energy usage in HA.  It's more a matter of interest than necessity but useful to know.
thanks

**Comment by js-yangjiabao** [comment]
@OrangeTux Great, I finally read about integrating ocpp into ha on github. Can you write a rich example about this? I also have a charging pile. I want to connect it to ha, but I don't know where to add information such as the id of the central system. Can you explain more about this? Thank you very much.

**Comment by OrangeTux** [comment]
>  Can you write a rich example about this?

What do you want from a 'rich example'? As I don't use HA I had a hard time to figure out what users would expect from the integration.

>  but I don't know where to add information such as the id of the central system. 

I'm not sure what you mean with 'id of the central system'. The CSMS doesn't has an ID. BY default the server [listens on port 9000](https://github.com/OrangeTux/core/blob/add-ocpp-support/homeassistant/components/ocpp/sensor.py#L85-L90). 

Let me know if you have more questions.

**Comment by js-yangjiabao** [comment]
Slip of the tongue For the central system ID, it should be the charging point ID. If I have two or more charging piles, I want to connect them to HA. I need to use their ID to distinguish them. Should this information be written in the configuration file? How to write it?

**Comment by js-yangjiabao** [comment]
I have an EN+ charging pile. I want to connect it to the homeassistant. I have already connected it to wifi. Next, I will configure the configuration file and write custom components. Finally, some information about the charging pile can be displayed at the front end of hass and the charging current can be set. But I don't know how to edit the configuration file and add some information to your source code. Is this information the ID of the charging pile? IP address? Or is it my mobile phone number? e-mail？

**Comment by OrangeTux** [comment]
Currently the plugin only supports a single charger. You don't need to configure the charger ID, the plugin accepts all IDs. 

Currently you can configure much. Only the port where the server will listen on (defaults to 9000), the measurands you want to display in the HA UI. And the refresh rate of those measurands.

If you want to add more configuration options you've to edit [this section](https://github.com/OrangeTux/core/blob/add-ocpp-support/homeassistant/components/ocpp/sensor.py#L52-L59). 

Every entry in the `PLATFORM_SCHEMA` dictionary corresponds to a configuration option in HA's config file. If you want to add more options you need to [pick a name for the key](https://github.com/home-assistant/core/blob/dev/homeassistant/const.py). Also you need to configure the [type of the configuration value](https://github.com/home-assistant/core/blob/dev/homeassistant/helpers/config_validation.py).

**Comment by js-yangjiabao** [comment]
Oh ~ great, maybe you made me fall in love with this platform and praised your reply speed.
Now I still need to make a load that matches the charging pile. Is it because I don't have a load that the charging pile works, so it shows unknown in my integration? Then where should those icons be set?
Well done! I'm a kid who's only been in contact with homeassistant for half a year. I believe I will love it in the future!

**Comment by OrangeTux** [comment]
> Now I still need to make a load that matches the charging pile. Is it because I don't have a load that the charging pile works, so it shows unknown in my integration?

I'm not exactly sure what you mean by this. But normally if a charger is charging it sends MeterValues requests to the Central System. These request contain transaction related metrics, called measurands in OCPP. An example is the measurand 'Current.Import' that contains the amount of current flowing into the car. 

You can configure which measurands you want to show in the HA UI using the config option `monitored_variables`. Note that most chargers don't send all different measurands possible. 

> Then where should those icons be set?

You can pick any of the [Material Design Icons](https://materialdesignicons.com/).

**Comment by js-yangjiabao** [comment]
I bought the AC charging pile to test the load instead of the electric car, but the monitored variables on HA are unknown.
The configuration file is as follows:
`sensor:
  - platform: ocpp
    port: 9000
    scan_interval:
      seconds: 10
    monitored_variables:
      - "Current.Export"`
sensor.py   the modified part
`MEASURANDS = {
    "Current.Export": ["Current.Export", "mdi:flash-auto"]
}`
`class ChargeMetric(Entity):
    """Sensor for charge metrics."""

    def __init__(self, measurand, data):
        """Instantiate instance of a ChargeMetrics."""
        #pdb.set_trace()
        self.measurand = MEASURANDS[measurand][0]
        self._icon = MEASURANDS[measurand][1]  
        self.data = data
        self._state = None`
I want to add the icon of monitoring variable, and I think this is no problem, but the front end of HA shows unknown.
![`Y2%~6~GT0LK5H7R8 )8P9](https://user-images.githubusercontent.com/70205502/98512428-41907f80-22a1-11eb-84d0-1997efa32c04.png)

**Comment by js-yangjiabao** [comment]
I don't have an electric car，so I bought an AC charging pile to test the load instead of an electric car, but the monitored variables on HA are unknown.
sensor.py the modified part:
`MEASURANDS= {
"Current.Export": ["Current.Export", "mdi:flash-auto"]
}` 

`class ChargeMetric(Entity):
 def init(self, measurand, data):
 self.measurand = MEASURANDS[measurand][0]
 self._icon = MEASURANDS[measurand][1]
 self.data = data
 self._state = None` 
I want to add the icon of monitoring variable, and I think this is no problem, but the front end of HA shows unknown. 
![Y2%6GT0LK5H7R8 )8P9](https://user-images.githubusercontent.com/70205502/98512428-41907f80-22a1-11eb-84d0-1997efa32c04.png)

**Comment by tropxy** [comment]
Hi, I am not familiar with HA apps, but the measurand you chose to extract is not the one that will provide you the current consumed by the EV. The one you are looking for is "Current.Import". By definition, Import and Export are in the perspective of the EV and not the Charging Station, thus Current.Import could be translated to "current being imported by the EV"

Could you also provide more info about the AC load you are using? like a link to the description of that device?
Thanks!

**Comment by js-yangjiabao** [comment]
@OrangeTux 
Hi, I will explain the above comments
I want to show the information I need on HA according to OrangeTux's idea, such as charging current, voltage and other parameters. He successfully displayed the parameter current.import When charging a car, I will see the charging current in the timeline, but I copied the file he linked to my own custom_component file, and also configured the information in configuration.yaml . turn on the AC charging pile load and set the current (this behavior simulates charging a car with charging piles). Then charge successfully, but some information displayed on my HA is unknown. Under normal circumstances, it should be the same as Mr. OrangeTux's example. I don't know where the problem lies.
Or let HA successfully display the size of the controlled measured value, besides what I said above, what other steps are needed?
@tropxy 
I'm glad you saw my comments and replied to me.
I quite agree with you, this is the link of the AC load I bought.[http://www.cniux.com/index.aspx](url)

**Comment by js-yangjiabao** [comment]
I didn't realize the integration of charging pile into HA. I got the following information after simulating the client running Python program:
![image](https://user-images.githubusercontent.com/70205502/98914762-fde98000-2503-11eb-87d3-8e53f38d0825.png)

**Comment by lbbrhzn** [comment]
i've created a HACS compatible repository for the home assistant plugin here:

https://github.com/lbbrhzn/ocpp

I can see BootNitifications, Hartbeat, StatusNotifications from my Wallbox PulsarPlus, but no measurands yet.

**Comment by OrangeTux** [comment]
Great! I will check it out later.

**Comment by angelsanchezz** [comment]
> i've created a HACS compatible repository for the home assistant plugin here:
> 
> https://github.com/lbbrhzn/ocpp
> 
> I can see BootNitifications, Hartbeat, StatusNotifications from my Wallbox PulsarPlus, but no measurands yet.

I can't add this repository to HACS, it tells me that the structure is invalid.

Any solution?

Thanks

**Comment by lbbrhzn** [comment]
> I can't add this repository to HACS, it tells me that the structure is invalid.
> 
> Any solution?

Solved now. Please note that this integration is highly experimental. It's my first python project and my first home assistant integration. Any help on improving it is highly appreciated!
