### ISSUE TITLE
Adding GUI for the OCPP client and server 

### ISSUE THREAD

**Issue by id4github** [mobilityhouse/ocpp#20]
I have developed OCPP client and server with this awesome library. I wanted to add GUI to the client and server. I intend to use React as frontend and Flask as backend for the application.
How to integrate OCPP python client with Flask framework. As the OCPP has its event loop running continuously blocking the flask code. Please help.
![git_up](https://user-images.githubusercontent.com/8154998/62211992-826ec880-b3bd-11e9-851d-e705cdb4d29f.png)

**Comment by OrangeTux** [comment]
Thanks for your compliment.

Unfortunately Flask and this package don't mix very well because Flask is sync and this package is async.

But I experimented a bit with using this package together with [Quart](https://pgjones.gitlab.io/quart/). Quart is a async web framework with a very similar API to Flask. 

There is some very ugly code over [on my personal profile](https://github.com/OrangeTux/CS).
Note that it probably doesn't work anymore with the current release of the ocpp package, but I think you can learn from the approach.

**Comment by tropxy** [comment]
Hey @id4github thanks for your interest. As Auke said, flask doesnt blend so well, but maybe aiohttp can be an option. They have also an api that can mimic flask operations... maybe you can check it out: [https://docs.aiohttp.org/en/stable/faq.html](https://docs.aiohttp.org/en/stable/faq.html)

**Comment by id4github** [comment]
Thanks for the quick reply. I will try these options(Quart , aiohttp).

**Comment by OrangeTux** [comment]
Great! I will close this issue for now. Feel free to reopen this one or create a new issue if you have questions.

**Comment by OrangeTux** [comment]
For people landing on this question. I've created a small example of an CSMS integrated with an HTTP API using `aiohttp`. The code can be found in [this comment](https://github.com/mobilityhouse/ocpp/issues/86#issuecomment-620205346),

**Comment by bosscoekku** [comment]
> For people landing on this question. I've created a small example of an CSMS integrated with an HTTP API using `aiohttp`. The code can be found in [this comment](https://github.com/mobilityhouse/ocpp/issues/86#issuecomment-620205346),

Could you please share the aiohttp version?
because I have to try to refer to your code but it not working.

**Comment by OrangeTux** [comment]
The `aiohttp` version is shared in the comment I linked in my previous post.
