### ISSUE TITLE
setup.py file missing

### ISSUE THREAD

**Issue by nandal4246** [mobilityhouse/ocpp#22]
Hi - I want to download and install the package manually and all over internet my research showing this project is missing setup.py file. Please guide if the request is meaningless.

**Comment by OrangeTux** [comment]
Hello @nandal4246 

Thanks for your question. This project uses `pyproject.toml` file in favor of `setup.py`. Instead of using `python setup.py install` you can use pip to install the package.

First make sure your version of pip is up to date. At least pip version 19 is required. You can upgrade your pip version using

```
$ pip install --upgrade pip
```

Now you can run the following command in the folder with the `pyproject.toml` file.

```
$ pip install .
```

While typing this I realize that there pip has no equivalent of `python setup.py develop`, which installs the package in editable mode. Do you need editable mode?
