### ISSUE TITLE
How to add the number of evses and connectors

### ISSUE THREAD

**Issue by betovaca** [mobilityhouse/ocpp#298]
Hello I'm a newbie in OCPP protocol. I already read all the protocol but there are some (maybe dumb) questions I was wondering:

- How do you know how many connectors and evses does the CS has?
- Do we need to store the variables in a new file or on the same program of the CS?
- These variables have standardized names or can we name them like 'evse_number'/'connector_number'?

Thanks for your help!

**Comment by OrangeTux** [comment]
> How do you know how many connectors and evses does the CS has?

In OCPP you could try to read the configuration 'NumberOfConnectors'. [See section 9.1.19 of the OCPP spec.](https://raw.githubusercontent.com/mobilityhouse/ocpp/master/docs/v16/ocpp-1.6.pdf). I don't know if such setting exists for OCPP 2.0.1.

> Do we need to store the variables in a new file or on the same program of the CS?
> These variables have standardized names or can we name them like 'evse_number'/'connector_number'?

I'm not sure what you mean by 'these variables'. Please elaborate.

**Comment by betovaca** [comment]
Thank you for your answer! I checked again and there's no such 'NumberOfConnectors' for OCPP 2.0.1.

When I mean variables I talk about the 'standard configuration Keys Names and Values'. That's how I understand it. 
These 'Keys Names' are my only blocking point. I can't understand them.

**Comment by proelke** [comment]
In 2.0.1 this data is stored in the device model.

**Comment by betovaca** [comment]
> In 2.0.1 this data is stored in the device model.

Yeah I see that but I'm not sure how to implement it. Is there any way to have an example? 
The list of components are python classes? 
Thanks in advance!

**Comment by proelke** [comment]
I don't believe there are any public implementations out there. Unfortunately its a bit hard to find inspiration to model it after, and most companies seem to keep the implementation close to the vest. You could certainly model the data using python classes, json, a dict, etc. It just depends on the design of the application.

**Comment by Jared-Newell-Mobility** [comment]
With OCPP 2.0.1 - under section 2.13. charging infrastructure related components and variables, here are the component type with names ChargingStation, EVSE and Connector, that accept the variable name Available - if the component exist True is returned.  By using a GetVariableDataType in section 2.25. the component with the variable can be queried. I would expect this to be combined with a looping structure to understand what the charge point has. These components as per OCPP must be implemented as a minimum, so the charge station should support this.

Use OCPP 2.0.1 Section 4. Device Model: Addressing Components and Variables to assist in implementing the above. 

In addition, section 7. numbering can be referenced to break out of the looping structure because of EVSE numbering, connector numbering constraints.
