### ISSUE TITLE
Working with real EVSE ?

### ISSUE THREAD

**Issue by stig888881** [mobilityhouse/ocpp#367]
Hello, can anyone share how this library works with real EVSE? Are you particularly interested in working with Remote Start Transaction ? As far as I understand, to activate this function, you need to disconnect and restart, but with: await asyncio.gather(cp.start(), cp.remote_start_transaction()). In this case , how do real devices that support OCPP react ?

**Comment by Jared-Newell-Mobility** [comment]
In this library examples of connectivity between an EVSE (Charge Point) and a Central System are given. The version of OCPP will need to be determined, that is support by the EVSE. By extending the central system provided in this library with a remote start transaction and setting up connectivity between the central system and the EVSE, this can be the path to achieve your goal. The OCPP documentation should be consulted. - Due to the time passed I will close this for now
