### ISSUE TITLE
Add support for OCPP 2.0 erratta 2

### ISSUE THREAD

**Issue by geekpi** [mobilityhouse/ocpp#73]
```
"transactionData": {
      "$ref": "#/definitions/TransactionType"
    },

"required": [
    "eventType",
    "timestamp",
    "triggerReason",
    "seqNo",
    "transactionData"
  ]
```

Field "transactionData" should be "transactionInfo" in ocpp 2.0.  Could you help to update the schema with lastest specification (v2.0.1)? Thanks

**Comment by OrangeTux** [comment]
Thanks for filing this issue. Although your request seem small, it might be a more work than it seems.

OCPP 2.0.1 is a different version than OCPP 2.0 and we need to support the whole version. This means that 

* [ocpp.messages.get_schema](https://github.com/mobilityhouse/ocpp/blob/master/ocpp/messages.py#L95-L134) must be modified. 
* The schemas of OCPP 2.0.1 must be added to the package
* Create and/or modify the dataclass for CALLs and CALLRESULTs. I haven't looked at the change set between OCPP 2.0 and OCPP 2.0.1. So I don't know whether we should reuse the  dataclasses from the `v20` module or we should recreate them for `v201`.

**Comment by tropxy** [comment]
Hi, 

Unfortunately, we should recreate our payloads from the V201 version, since there are some considerable changes between versions.

At the moment, we dont have support for OCPP 2.0.1, however I would avoid adding official support to it for now, since the final version of the standard was not released yet. Currently, the standard is in RC 2 (release candidate 2nd version stage). However, maybe we could have a branch dedicated for it, so that people can use it...what do you think @OrangeTux ?

**Comment by OrangeTux** [comment]
Good idea @tropxy! I think that is a good way to start implementing OCPP 2.0.1.

One drawback is, of course, that people that want to use this branch have pin there requirements to this specific branch or commit. Not sure, but maybe we can use a similar strategy as the language Go does for experimental packages. [They put all the experimental packages in there own namespace called x](https://pkg.go.dev/golang.org/x/exp). We could do the same and create a package like `ocpp.x.v201` or `ocpp.exp.v201`. We can put this in the master branch, but with a note that code in this namespace is subjective to backwards incompatible changes.

**Comment by tropxy** [comment]
Yeah, I like that idea!! I would go for the ocpp.exp.v201 (ocpp.x. can be confusing, because in the spec they refer a few times to ocpp 1.x versions...)

**Comment by geekpi** [comment]
@OrangeTux  In lastest errata of OCPP 2.0 (not 2.0.1), this field was changed to transactionInfo.

**Comment by tropxy** [comment]
That is correct. Auke if you want to check, I have added the errata (page 53)

[OCPP-2.0_part2_errata.pdf](https://github.com/mobilityhouse/ocpp/files/4338358/OCPP-2.0_part2_errata.pdf)

However, @geekpi by the time we have published v2.0 here, we have tested it in the Plugfest event hosted by Elaad NL and we have decided to support just the v2.0 and not the Errata. Currently, I dont see that ElaadNL has provided the json schemas for the errata in the OCA website, but they have provided the errata pdf document.

It is a bit of a mess in my POV, because 
1) the errata provided in the OCA public download space is not up to date to the one present in the OCA Tech WG documents page (for members)

2) There are no Json Schemas present in the OCA public download space. I have the schemas provided in October during the Plugfest ([JSON_schemas_errata_sheet_release_candidate.zip](https://github.com/mobilityhouse/ocpp/files/4338426/JSON_schemas_errata_sheet_release_candidate.zip))

3) The Json Schemas Release candidate for 2.0 in the OCA members are for download is also different from the version I provided above.

Given all of this, I would may request for updated Json Schemas in the OCA public download page before doing any modifications to our code base.

**Comment by OrangeTux** [comment]
I think I slowly getting. OCPP 2.0.1 RC is something different than the OCPP 2.0 Errata 2.

But no I am a bit confused now by the OCA. Do they really introduce backward incompatible changes in erratas of OCPP 2.0? How do client and server agree on which errata they implement? For as far as I understand it there us currently no way to exchange that information, correct?

**Comment by tropxy** [comment]
For your first question, yes, there is the OCPP 2.0 errata and now the OCPP 2.0.1 which shall substitute OCPP 2.0.
TBH, I dont know if the different errata versions are backward incompatible or not, I just know that there are different document versions and not all the documents are public accessible.

**Comment by tropxy** [comment]
Given the fact that OCPP 2.0.1 has been released, we dont have to deal with this problem anymore and I will close this issue.

**Comment by OrangeTux** [comment]
I disagree with this. I think we should have support for both versions. I agree with you that people ideally should use OCPP 2.0.1 over OCPP 2.0 if they have a choice. But people might not have that choice. Maybe the charge point they interact with supports OCPP 2.0 and not OCPP 2.0.1.

As library creators we shouldn't decide on what version someone should use. That is up the user itself.

Therefore I think we should support both versions.

**Comment by geekpi** [comment]
Does anyone have ocpp 2.0 documentation? I found it was replaced by 2.0.1. I can't download it anymore.

**Comment by OrangeTux** [comment]
@geekpi Here you go 
[OCPP_2.0_Specification.zip](https://github.com/mobilityhouse/ocpp/files/4812313/OCPP_2.0_Specification.zip)
