### ISSUE TITLE
How can I implement create a new thread to send heartbeat continuously 

### ISSUE THREAD

**Issue by JavanWang** [mobilityhouse/ocpp#80]
How can I implement create a new thread to send heartbeat continuously?
I had tried multiple methods but always stuck in "asyncio". I don't understand "asyncio" clearly really.
Would you write a sample code?

``` python
class ChargePoint(cp):

    async def heartbeatFunc(self):

        while True:
            try:
                request = call.HeartbeatPayload() 
                #raise runtime error attached to a different loop                               
                response = await self.call(request)
                await asyncio.sleep(60*5)
            except:
                raise
  
    async def send_boot_notification(self):

        request = call.BootNotificationPayload(
            charge_point_model="sample",
            charge_point_vendor="test"
        )
        response = await self.call(request)
        #heartbeat on main thread ok
        request = call.HeartbeatPayload()
        response = await self.call(request)
        #send beartbeat on new thread time interval continuously ng
        _thread.start_new_thread(self.heartbeatFunc, ())
```

**Comment by OrangeTux** [comment]
Mixing ascynio with threads can be tricky. So I would avoid that if possible. 

Instead of running `ChargePoint.heartbeatFunc()` in a new thread you should run it on the event loop of your main thread. For Python 3.7+ you can use [asyncio.create_task](https://docs.python.org/3/library/asyncio-task.html?highlight=asyncio%20task#asyncio.create_task). Fr older versions you can use [asyncio.ensure_future](https://docs.python.org/3/library/asyncio-future.html#asyncio.ensure_future).

``` python
 async def send_boot_notification(self):

        request = call.BootNotificationPayload(
            charge_point_model="sample",
            charge_point_vendor="test"
        )
        response = await self.call(request)
        #heartbeat on main thread ok
        request = call.HeartbeatPayload()
        response = await self.call(request)
        #send beartbeat on new thread time interval continuously ng
        asyncio.create_task(self.heartbeatFunc())
```

Getting back to the exception in your example: `RuntimeError: Task attached to a different loop`.
In order to understand that you must know that tasks and coroutines are executed on an event loop. There are several ways to start an event loop. But normally you start that event loop with [asyncio.run](https://docs.python.org/3/library/asyncio-task.html?highlight=asyncio%20task#asyncio.run) in Python 3.7+ or [asyncio.run_until_complete](https://docs.python.org/3/library/asyncio-eventloop.html?highlight=run_until_complete#asyncio.loop.run_until_complete) if you use an older version of Python.

This event loop is bound to a thread. All the tasks are also bound to that event loop. In the code example you moved moved a coroutine to a different thread to execute it there. That is not possible.
Therefore again my advice to avoid asyncio and threads.

**Comment by JavanWang** [comment]
Amazing!
I have struggled with asynchronous / threading for almost a week,
you solve my problem in one line code.
